services:
  postgres:
    image: postgres:14
    container_name: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user" ]
      interval: 5s
      timeout: 2s
      retries: 60
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: rufusy/spring-data-jpa-tutorial
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: